name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run pytest
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q

    - name: Start FastAPI with uvicorn (smoke test)
      run: |
        nohup uvicorn src.app:app --port 8080 --log-level warning &
        sleep 5
        curl -f http://127.0.0.1:8080/
